import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { z } from "zod";

import { redactSensitiveText } from "../lib/redact.js";

const outputDirSchema = z
  .string()
  .trim()
  .min(1)
  .describe("Directory where scaffold files should be written.")
  .refine((value) => {
    const normalized = resolve(value).replace(/\\/g, "/");
    if (normalized === "/" || normalized === "/root" || normalized === "/etc") return false;
    const restrictedPrefixes = ["/etc/", "/proc/", "/sys/", "/dev/", "/root/", "/boot/", "/var/log/", "/run/"];
    return !restrictedPrefixes.some((prefix) => normalized.startsWith(prefix));
  }, {
    message: "Output directory targets a restricted system path."
  });

const nameSchema = z
  .string()
  .trim()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z][A-Za-z0-9_-]*$/, "Name must start with a letter and contain only letters, numbers, '_' or '-'.");

type ScaffoldFile = {
  path: string;
  content: string;
};

function toSnakeName(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase() || "hello_world";
}

function toPascalName(name: string): string {
  return toSnakeName(name)
    .split("_")
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("") || "HelloWorld";
}

function toKebabName(name: string): string {
  return toSnakeName(name).replace(/_/g, "-");
}

export function writeScaffoldFiles(outputDir: string, files: ScaffoldFile[], overwrite: boolean): string[] {
  const root = resolve(outputDir);
  const written: string[] = [];

  for (const file of files) {
    const absolutePath = resolve(root, file.path);
    if (!absolutePath.startsWith(`${root}/`) && absolutePath !== root) {
      throw new Error(`Refusing to write outside outputDir: ${file.path}`);
    }
    if (!overwrite && existsSync(absolutePath)) {
      throw new Error(`Refusing to overwrite existing file: ${absolutePath}`);
    }
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, file.content, "utf8");
    written.push(absolutePath);
  }

  return written;
}

export function sorobanContractFiles(contractName: string): ScaffoldFile[] {
  const crateName = toSnakeName(contractName);
  const contractStruct = `${toPascalName(contractName)}Contract`;

  return [
    {
      path: "Cargo.toml",
      content: `[workspace]
resolver = "2"
members = ["contracts/${crateName}"]

[workspace.package]
edition = "2021"
rust-version = "1.84"

[workspace.dependencies]
soroban-sdk = "23.0.0"

[profile.release]
overflow-checks = true
`
    },
    {
      path: ".gitignore",
      content: `/target
**/*.wasm
**/*.optimized.wasm
`
    },
    {
      path: `contracts/${crateName}/Cargo.toml`,
      content: `[package]
name = "${crateName}"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
`
    },
    {
      path: `contracts/${crateName}/src/lib.rs`,
      content: `#![no_std]

use soroban_sdk::{contract, contractimpl, symbol_short, Env, Symbol};

#[contract]
pub struct ${contractStruct};

#[contractimpl]
impl ${contractStruct} {
    pub fn hello(env: Env, to: Symbol) -> Symbol {
        let _ = env;
        to
    }

    pub fn increment(env: Env) -> u32 {
        let key = symbol_short!("COUNT");
        let count: u32 = env.storage().persistent().get(&key).unwrap_or(0);
        let next = count + 1;
        env.storage().persistent().set(&key, &next);
        next
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{symbol_short, Env};

    #[test]
    fn hello_returns_symbol() {
        let env = Env::default();
        let id = env.register(${contractStruct}, ());
        let client = ${contractStruct}Client::new(&env, &id);

        assert_eq!(client.hello(&symbol_short!("Julio")), symbol_short!("Julio"));
    }

    #[test]
    fn increment_counts() {
        let env = Env::default();
        let id = env.register(${contractStruct}, ());
        let client = ${contractStruct}Client::new(&env, &id);

        assert_eq!(client.increment(), 1);
        assert_eq!(client.increment(), 2);
    }
}
`
    },
    {
      path: "README.md",
      content: `# ${contractStruct}

Soroban smart contract scaffold generated by Stellar MCP.

## Requirements

- Rust 1.84 or newer
- wasm32v1-none target: \`rustup target add wasm32v1-none\`
- Stellar CLI 27.x

## Commands

\`\`\`bash
cargo test
stellar contract build
stellar contract deploy \\
  --wasm target/wasm32v1-none/release/${crateName}.wasm \\
  --source <stellar-cli-key-name> \\
  --network testnet
stellar contract bindings typescript \\
  --contract-id <CONTRACT_ID> \\
  --output-dir ./packages/${toKebabName(contractName)} \\
  --overwrite
\`\`\`

Use the generated TypeScript bindings from a Next.js frontend instead of hand-encoding contract arguments.
`
    }
  ];
}

export function nextWalletFiles(appName: string): ScaffoldFile[] {
  const packageName = toKebabName(appName);

  return [
    {
      path: "package.stellar-snippet.json",
      content: `{
  "scripts": {
    "dev": "next dev --experimental-https"
  },
  "dependencies": {
    "@stellar/freighter-api": "latest",
    "@stellar/stellar-sdk": "latest"
  }
}
`
    },
    {
      path: ".env.local.example",
      content: `NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
NEXT_PUBLIC_STELLAR_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
NEXT_PUBLIC_STELLAR_CONTRACT_ID=
# Server-only local test wallet. Never expose through NEXT_PUBLIC_* and never commit .env.local.
STELLAR_TEST_PUBLIC_KEY=
STELLAR_TEST_SECRET_KEY=
`
    },
    {
      path: "scripts/create-test-wallet.mjs",
      content: `#!/usr/bin/env node
import { Keypair } from "@stellar/stellar-sdk";

const shouldFund = process.argv.includes("--fund");
const keypair = Keypair.random();
let funding = null;

if (shouldFund) {
  const response = await fetch(\`https://friendbot.stellar.org?addr=\${encodeURIComponent(keypair.publicKey())}\`);
  if (!response.ok) {
    const body = await response.text();
    throw new Error(\`Friendbot failed (\${response.status}): \${body}\`);
  }
  funding = await response.json();
}

console.log("# Testnet wallet. Paste into .env.local only. Never commit it.");
console.log(\`STELLAR_TEST_PUBLIC_KEY=\${keypair.publicKey()}\`);
console.log(\`STELLAR_TEST_SECRET_KEY=\${keypair.secret()}\`);
console.log("STELLAR_NETWORK=testnet");
if (funding) {
  console.error(\`Friendbot funded account in ledger \${funding.ledger ?? "unknown"}\`);
}
`
    },
    {
      path: "lib/stellar/network.ts",
      content: `import { Networks } from "@stellar/stellar-sdk";

export type StellarNetwork = "testnet" | "mainnet";

export const stellarNetwork = (process.env.NEXT_PUBLIC_STELLAR_NETWORK ?? "testnet") as StellarNetwork;

export const stellarNetworkPassphrase =
  process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE ??
  (stellarNetwork === "mainnet" ? Networks.PUBLIC : Networks.TESTNET);

export const stellarRpcUrl =
  process.env.NEXT_PUBLIC_STELLAR_RPC_URL ??
  (stellarNetwork === "mainnet" ? "https://soroban.stellar.org" : "https://soroban-testnet.stellar.org");

export const stellarHorizonUrl =
  process.env.NEXT_PUBLIC_STELLAR_HORIZON_URL ??
  (stellarNetwork === "mainnet" ? "https://horizon.stellar.org" : "https://horizon-testnet.stellar.org");
`
    },
    {
      path: "lib/stellar/contract.ts",
      content: `import { stellarNetwork } from "./network";

export const stellarContractId = process.env.NEXT_PUBLIC_STELLAR_CONTRACT_ID ?? "";

export function requireContractId(): string {
  if (!stellarContractId) {
    throw new Error("Missing NEXT_PUBLIC_STELLAR_CONTRACT_ID. Deploy the Soroban contract and generate TypeScript bindings first.");
  }
  return stellarContractId;
}

export function contractBindingNotes() {
  return {
    network: stellarNetwork,
    contractId: stellarContractId || "<CONTRACT_ID>",
    command: "stellar contract bindings typescript --contract-id <CONTRACT_ID> --output-dir ./packages/<contract-name> --overwrite",
    rule: "Import generated bindings from ./packages/<contract-name>; do not hand-encode XDR in UI code."
  };
}
`
    },
    {
      path: "hooks/useStellarWallet.ts",
      content: `"use client";

import { useCallback, useMemo, useState } from "react";
import { getAddress, isConnected, requestAccess, signTransaction } from "@stellar/freighter-api";

import { stellarNetwork, stellarNetworkPassphrase } from "../lib/stellar/network";

type FreighterError = { message?: string };
type FreighterResult<T> = T & { error?: FreighterError };

export type StellarWalletState = {
  address: string | null;
  connected: boolean;
  connecting: boolean;
  error: string | null;
};

function errorMessage(error: unknown): string {
  if (!error) return "Unknown wallet error";
  if (typeof error === "string") return error;
  if (typeof error === "object" && "message" in error) {
    return String((error as { message?: unknown }).message ?? "Unknown wallet error");
  }
  return "Unknown wallet error";
}

function readConnected(result: unknown): boolean {
  if (typeof result === "boolean") return result;
  if (result && typeof result === "object" && "isConnected" in result) {
    return Boolean((result as { isConnected?: unknown }).isConnected);
  }
  return false;
}

export function useStellarWallet() {
  const [state, setState] = useState<StellarWalletState>({
    address: null,
    connected: false,
    connecting: false,
    error: null
  });

  const refresh = useCallback(async () => {
    const connectedResponse = await isConnected();
    const connected = readConnected(connectedResponse);
    const addressResponse = await getAddress() as FreighterResult<{ address?: string }>;
    const address = addressResponse.error ? null : addressResponse.address ?? null;

    setState((current) => ({
      ...current,
      connected,
      address,
      error: addressResponse.error ? errorMessage(addressResponse.error) : null
    }));

    return { connected, address };
  }, []);

  const connect = useCallback(async () => {
    setState((current) => ({ ...current, connecting: true, error: null }));
    try {
      const connectedResponse = await isConnected();
      if (!readConnected(connectedResponse)) {
        throw new Error("Freighter is not installed or not available in this browser.");
      }

      const access = await requestAccess() as FreighterResult<{ address?: string }>;
      if (access.error) throw new Error(errorMessage(access.error));
      if (!access.address) throw new Error("Freighter did not return an address.");

      setState({ address: access.address, connected: true, connecting: false, error: null });
      return access.address;
    } catch (error) {
      const message = errorMessage(error);
      setState((current) => ({ ...current, connecting: false, error: message }));
      throw error;
    }
  }, []);

  const disconnect = useCallback(() => {
    setState({ address: null, connected: false, connecting: false, error: null });
  }, []);

  const signXdr = useCallback(async (xdr: string) => {
    const address = state.address ?? (await connect());
    const signed = await signTransaction(xdr, {
      network: stellarNetwork.toUpperCase(),
      networkPassphrase: stellarNetworkPassphrase,
      address
    }) as FreighterResult<{ signedTxXdr?: string; signerAddress?: string }>;

    if (signed.error) throw new Error(errorMessage(signed.error));
    if (!signed.signedTxXdr) throw new Error("Freighter did not return a signed transaction XDR.");
    return signed;
  }, [connect, state.address]);

  return useMemo(() => ({
    ...state,
    refresh,
    connect,
    disconnect,
    signXdr
  }), [connect, disconnect, refresh, signXdr, state]);
}
`
    },
    {
      path: "components/stellar/WalletButton.tsx",
      content: `"use client";

import { useStellarWallet } from "../../hooks/useStellarWallet";

function shortAddress(address: string): string {
  return \`\${address.slice(0, 6)}...\${address.slice(-6)}\`;
}

export function WalletButton() {
  const wallet = useStellarWallet();

  return (
    <div className="flex items-center gap-3">
      <button
        type="button"
        onClick={() => wallet.connected ? wallet.disconnect() : wallet.connect()}
        disabled={wallet.connecting}
        className="rounded-md bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
      >
        {wallet.connecting
          ? "Connecting..."
          : wallet.connected && wallet.address
            ? shortAddress(wallet.address)
            : "Connect Freighter"}
      </button>
      {wallet.error ? <p className="text-sm text-red-600">{wallet.error}</p> : null}
    </div>
  );
}
`
    },
    {
      path: "app/stellar-demo/page.tsx",
      content: `import { WalletButton } from "../../components/stellar/WalletButton";
import { stellarNetwork, stellarRpcUrl } from "../../lib/stellar/network";

export default function StellarDemoPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col gap-6 px-6 py-12">
      <div>
        <p className="text-sm uppercase tracking-wide text-slate-500">{stellarNetwork}</p>
        <h1 className="text-3xl font-semibold">Stellar wallet demo</h1>
        <p className="mt-2 text-slate-600">Freighter connection scaffold for ${packageName}.</p>
      </div>
      <WalletButton />
      <div className="rounded-md border border-slate-200 p-4 text-sm text-slate-700">
        <div className="font-medium">RPC</div>
        <div className="break-all">{stellarRpcUrl}</div>
      </div>
    </main>
  );
}
`
    },
    {
      path: "README.stellar-nextjs.md",
      content: `# Stellar Next.js Wallet Components

Generated by Stellar MCP.

## Install dependencies

\`\`\`bash
npm install @stellar/freighter-api @stellar/stellar-sdk
\`\`\`

Freighter requires a secure browser context. For local Next.js development, use:

\`\`\`json
{
  "scripts": {
    "dev": "next dev --experimental-https"
  }
}
\`\`\`

Copy \`.env.local.example\` to \`.env.local\` and set \`NEXT_PUBLIC_STELLAR_CONTRACT_ID\` after deployment.

## Test wallets

Create a local testnet wallet for integration tests:

\`\`\`bash
node scripts/create-test-wallet.mjs --fund
\`\`\`

Paste the printed values into \`.env.local\` only. Never commit \`.env.local\`, \`STELLAR_TEST_SECRET_KEY\`, or any wallet seed. Do not expose test wallet secrets through \`NEXT_PUBLIC_*\`.

Use Stellar CLI TypeScript bindings for contract calls:

\`\`\`bash
stellar contract bindings typescript \\
  --contract-id <CONTRACT_ID> \\
  --output-dir ./packages/<contract-name> \\
  --overwrite
\`\`\`

After bindings are generated, import the generated client into server actions, API routes, or client code that signs through Freighter. Use \`lib/stellar/contract.ts\` to keep the active contract ID/network consistent.
`
    }
  ];
}

export function registerScaffoldTools(server: McpServer): void {
  server.tool(
    "stellar_soroban_scaffold_contract",
    "Create a Rust Soroban smart contract scaffold with tests and Stellar CLI build/deploy/bindings commands.",
    {
      outputDir: outputDirSchema,
      contractName: nameSchema.default("hello_world").describe("Contract/crate name to scaffold."),
      overwrite: z.boolean().default(false).describe("Overwrite existing scaffold files if they already exist.")
    },
    async ({ outputDir, contractName, overwrite }) => {
      try {
        const files = sorobanContractFiles(contractName);
        const writtenFiles = writeScaffoldFiles(outputDir, files, overwrite);
        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              status: "created",
              scaffold: "soroban-contract",
              contractName: toSnakeName(contractName),
              files: writtenFiles,
              nextSteps: [
                "rustup target add wasm32v1-none",
                "cargo test",
                "stellar contract build",
                "stellar contract deploy --wasm target/wasm32v1-none/release/<contract>.wasm --source <key> --network testnet",
                "stellar contract bindings typescript --contract-id <CONTRACT_ID> --output-dir ./packages/<contract> --overwrite"
              ]
            }, null, 2)
          }]
        };
      } catch (error) {
        return {
          isError: true,
          content: [{ type: "text", text: redactSensitiveText(error instanceof Error ? error.message : String(error)) }]
        };
      }
    }
  );

  server.tool(
    "stellar_nextjs_wallet_scaffold",
    "Create Next.js wallet components for Stellar/Freighter plus env and contract binding notes.",
    {
      outputDir: outputDirSchema,
      appName: nameSchema.default("stellar_dapp").describe("App name used in generated notes."),
      overwrite: z.boolean().default(false).describe("Overwrite existing scaffold files if they already exist.")
    },
    async ({ outputDir, appName, overwrite }) => {
      try {
        const files = nextWalletFiles(appName);
        const writtenFiles = writeScaffoldFiles(outputDir, files, overwrite);
        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              status: "created",
              scaffold: "nextjs-stellar-wallet",
              files: writtenFiles,
              dependencies: ["@stellar/freighter-api", "@stellar/stellar-sdk"],
              nextSteps: [
                "npm install @stellar/freighter-api @stellar/stellar-sdk",
                "use next dev --experimental-https for local Freighter testing",
                "copy .env.local.example to .env.local",
                "generate Stellar CLI TypeScript bindings after deploying a Soroban contract"
              ]
            }, null, 2)
          }]
        };
      } catch (error) {
        return {
          isError: true,
          content: [{ type: "text", text: redactSensitiveText(error instanceof Error ? error.message : String(error)) }]
        };
      }
    }
  );
}
